ys001.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 0
  subtaskId: 0

ys002.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 0
  subtaskId: 0

ys003.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 0
  subtaskId: 0

ys004.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 0
  subtaskId: 0

ys01.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 1

ys11.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 1

ys12.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 1

ys21.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 1

ys02.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 15
  subtaskId: 2

ys03.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 15
  subtaskId: 2

ys13.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 15
  subtaskId: 2

ys14.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 15
  subtaskId: 2

ys22.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 15
  subtaskId: 2

ys32.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 15
  subtaskId: 2

ys05.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 15
  subtaskId: 3

ys15.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 15
  subtaskId: 3

ys16.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 15
  subtaskId: 3

ys23.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 15
  subtaskId: 3

ys33.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 15
  subtaskId: 3

ys06.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 25
  subtaskId: 4

ys07.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 25
  subtaskId: 4

ys17.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 25
  subtaskId: 4

ys18.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 25
  subtaskId: 4

ys24.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 25
  subtaskId: 4

ys34.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 25
  subtaskId: 4

ys08.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 25
  subtaskId: 6

ys09.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 25
  subtaskId: 6

ys19.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 25
  subtaskId: 6

ys110.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 25
  subtaskId: 6

ys25.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 25
  subtaskId: 6

ys35.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 25
  subtaskId: 6

ys41.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 5

ys42.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 5

ys43.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 5

ys44.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 5

ys45.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 5

ys46.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 5

ys47.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 5

ys48.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 5

ys49.in:
  timeLimit: 1000
  memoryLimit: 524288
  score: 10
  subtaskId: 5