bhxqtd001.in:
  timeLimit: 1000
  memoryLimit: 262144
  score: 0
  subtaskId: 0

bhxqtd002.in:
  timeLimit: 1000
  memoryLimit: 262144
  score: 0
  subtaskId: 0

bhxqtd01.in:
  timeLimit: 1000
  memoryLimit: 262144
  score: 10
  subtaskId: 1

bhxqtd02.in:
  timeLimit: 1000
  memoryLimit: 262144
  score: 10
  subtaskId: 1

bhxqtd03.in:
  timeLimit: 1000
  memoryLimit: 262144
  score: 10
  subtaskId: 2

bhxqtd04.in:
  timeLimit: 1000
  memoryLimit: 262144
  score: 10
  subtaskId: 2

bhxqtd05.in:
  timeLimit: 1000
  memoryLimit: 262144
  score: 40
  subtaskId: 3

bhxqtd06.in:
  timeLimit: 1000
  memoryLimit: 262144
  score: 40
  subtaskId: 3

bhxqtd07.in:
  timeLimit: 1000
  memoryLimit: 262144
  score: 40
  subtaskId: 3

bhxqtd08.in:
  timeLimit: 1000
  memoryLimit: 262144
  score: 40
  subtaskId: 3

bhxqtd09.in:
  timeLimit: 1000
  memoryLimit: 262144
  score: 40
  subtaskId: 3

bhxqtd10.in:
  timeLimit: 1000
  memoryLimit: 262144
  score: 40
  subtaskId: 3

bhxqtd13.in:
  timeLimit: 1000
  memoryLimit: 262144
  score: 10
  subtaskId: 5

bhxqtd14.in:
  timeLimit: 1000
  memoryLimit: 262144
  score: 10
  subtaskId: 5

bhxqtd15.in:
  timeLimit: 1000
  memoryLimit: 262144
  score: 30
  subtaskId: 6

bhxqtd16.in:
  timeLimit: 1000
  memoryLimit: 262144
  score: 30
  subtaskId: 6

bhxqtd17.in:
  timeLimit: 1000
  memoryLimit: 262144
  score: 30
  subtaskId: 6

bhxqtd18.in:
  timeLimit: 1000
  memoryLimit: 262144
  score: 30
  subtaskId: 6

bhxqtd20.in:
  timeLimit: 1000
  memoryLimit: 262144
  score: 30
  subtaskId: 6